# Site settings
title: Natural Language Process 
email: wangjialin@hust.edu.cn
description: "Projects about NLP "
#baseurl: ""
baseurl: "https://wangjialin114.github.io/nlp-tensorflow/"
url: ""
twitter_username: 
github_username:  wangjialin114

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

